TimerTest are more informative; upgrade to Studio 2 beta 4
New test will say by how much it failed, rather than the previous,
cryptic expected-true-but-was-false:

```
java.lang.AssertionError: Started, time elapsed should return should be
less than 60 ms
Expected: a value less than <60L>
but: <66L> was greater than <60L>
```